"""Self-contained HTML presentation of an :class:`AnalysisReport`.

This module does not run analysis. It only renders an existing report so a
future release can persist ``AnalysisReport`` (or ``report.to_dict()``) and
re-render HTML without re-analyzing the corpus.
"""

from __future__ import annotations

from collections import defaultdict
from html import escape
from typing import Any

from samyak.corpus.models import AnalysisReport, Finding, Severity

_SEVERITY_ORDER = (Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO)


def render_html_report(report: AnalysisReport) -> str:
    """Render a standalone, offline HTML report from ``report``."""
    summary = report.summary
    counts = report.severity_counts()
    grouped = _group_findings(report.findings)
    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f'<meta name="generator" content="{_e(report.product)} {_e(report.version)}">',
        "<title>Samyak Corpus Intelligence Report</title>",
        f"<style>{_CSS}</style>",
        "</head>",
        "<body>",
        "<header>",
        '<p class="eyebrow">Samyak by DataAIHub</p>',
        "<h1>Corpus Intelligence Report</h1>",
        '<p class="lede">Offline analysis of a local document corpus. '
        "Findings are review signals, not predictions of retrieval quality.</p>",
        "</header>",
        "<section>",
        "<h2>Run</h2>",
        _dl(
            [
                ("Product", report.product),
                ("Capability", report.capability),
                ("Version", report.version),
                ("Corpus root", summary.corpus_root),
            ]
        ),
        "</section>",
        "<section>",
        "<h2>Corpus summary</h2>",
        _summary_table(report),
        _extension_tables(report),
        _path_sample_block("Load errors", summary.load_errors, summary.load_error_paths),
        _path_sample_block(
            "Discovery errors",
            summary.discovery_errors,
            summary.discovery_error_paths,
        ),
        "</section>",
        "<section>",
        "<h2>Finding counts by severity</h2>",
        _severity_table(counts),
        "</section>",
        "<section>",
        "<h2>Findings</h2>",
        _findings_html(grouped),
        "</section>",
        "<section>",
        "<h2>Analysis configuration</h2>",
        _config_table(report.config),
        "</section>",
        "<footer>",
        "<p>Generated by Samyak "
        f'<span class="mono">{_e(report.version)}</span>. '
        "No network access or external assets are required to view this file.</p>",
        "</footer>",
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(parts)


def _e(value: object) -> str:
    return escape(str(value), quote=True)


def _dl(rows: list[tuple[str, object]]) -> str:
    items = "".join(f"<div><dt>{_e(label)}</dt><dd>{_e(value)}</dd></div>" for label, value in rows)
    return f'<dl class="meta">{items}</dl>'


def _summary_table(report: AnalysisReport) -> str:
    summary = report.summary
    rows = [
        ("Files discovered", summary.total_discovered_files),
        ("Supported files", summary.supported_files),
        ("Unsupported files", summary.unsupported_files),
        ("Documents analyzed", summary.analyzed_documents),
        ("Load errors", summary.load_errors),
        ("Discovery errors", summary.discovery_errors),
        ("Total characters", summary.total_characters),
        ("Total bytes", summary.total_bytes),
        ("Average characters", _fmt_float(summary.average_characters)),
        ("Median characters", _fmt_float(summary.median_characters)),
        ("Min characters", _fmt_optional_int(summary.min_characters)),
        ("Max characters", _fmt_optional_int(summary.max_characters)),
    ]
    body = "".join(f"<tr><th>{_e(label)}</th><td>{_e(value)}</td></tr>" for label, value in rows)
    return f'<table class="stats"><tbody>{body}</tbody></table>'


def _extension_tables(report: AnalysisReport) -> str:
    return "".join(
        [
            _count_table("Analyzed by extension", report.summary.analyzed_by_extension),
            _count_table("Unsupported by extension", report.summary.unsupported_by_extension),
        ]
    )


def _count_table(title: str, counts: dict[str, int]) -> str:
    if not counts:
        return f'<p class="muted">{_e(title)}: none</p>'
    rows = "".join(
        f"<tr><th>{_e(ext)}</th><td>{_e(count)}</td></tr>" for ext, count in counts.items()
    )
    return f'<h3>{_e(title)}</h3><table class="stats"><tbody>{rows}</tbody></table>'


def _path_sample_block(title: str, count: int, paths: tuple[str, ...]) -> str:
    heading = f"<h3>{_e(title)}</h3><p>Count: {_e(count)}</p>"
    if count == 0:
        return heading + f'<p class="muted">No {_e(title.lower())}.</p>'
    items = "".join(f"<li><code>{_e(path)}</code></li>" for path in paths)
    truncated = ""
    if count > len(paths):
        truncated = f'<p class="muted">Showing {len(paths)} of {_e(count)} paths.</p>'
    return f'{heading}<ul class="paths">{items}</ul>{truncated}'


def _severity_table(counts: dict[str, int]) -> str:
    rows = "".join(
        "<tr>"
        f'<th><span class="sev sev-{sev.value.lower()}">{_e(sev.value)}</span></th>'
        f"<td>{_e(counts[sev.value])}</td>"
        "</tr>"
        for sev in _SEVERITY_ORDER
    )
    return f'<table class="stats"><tbody>{rows}</tbody></table>'


def _group_findings(findings: tuple[Finding, ...]) -> list[tuple[str, list[Finding]]]:
    buckets: dict[str, list[Finding]] = defaultdict(list)
    order: list[str] = []
    for finding in findings:
        if finding.category not in buckets:
            order.append(finding.category)
        buckets[finding.category].append(finding)
    return [(category, buckets[category]) for category in order]


def _findings_html(grouped: list[tuple[str, list[Finding]]]) -> str:
    if not grouped:
        return "<p>No findings. The analyzed corpus did not trigger v0.1 checks.</p>"
    chunks: list[str] = []
    for category, findings in grouped:
        label = category.replace("_", " ")
        chunks.append(f"<h3>{_e(label)}</h3>")
        for finding in findings:
            chunks.append(_finding_article(finding))
    return "".join(chunks)


def _finding_article(finding: Finding) -> str:
    sev = finding.severity.value
    return "".join(
        [
            '<article class="finding">',
            "<header>",
            f'<span class="sev sev-{_e(sev.lower())}">{_e(sev)}</span> ',
            f'<code class="code">{_e(finding.code)}</code>',
            f"<h4>{_e(finding.title)}</h4>",
            "</header>",
            f"<p>{_e(finding.message)}</p>",
            "<h5>Why it matters</h5>",
            f"<p>{_e(finding.why_it_matters)}</p>",
            "<h5>Recommendation</h5>",
            f"<p>{_e(finding.recommendation)}</p>",
            _affected_block(finding),
            _evidence_block(finding),
            "</article>",
        ]
    )


def _affected_block(finding: Finding) -> str:
    total = finding.evidence.get("affected_document_count")
    if not isinstance(total, int):
        total = len(finding.affected_documents)
    paths = list(finding.affected_documents)
    if not paths and not total:
        return ""
    items = "".join(f"<li><code>{_e(path)}</code></li>" for path in paths)
    truncated = ""
    if bool(finding.evidence.get("affected_documents_truncated")) or total > len(paths):
        truncated = f'<p class="muted">Showing {len(paths)} of {_e(total)} documents.</p>'
    return f'<h5>Affected documents ({_e(total)})</h5><ul class="paths">{items}</ul>{truncated}'


def _evidence_block(finding: Finding) -> str:
    rendered = _render_evidence(finding.evidence)
    if not rendered:
        return ""
    return f"<h5>Evidence</h5>{rendered}"


_SKIP_EVIDENCE_KEYS = frozenset(
    {
        "sample_paths",
        "affected_document_count",
        "affected_documents_truncated",
    }
)


def _render_evidence(evidence: dict[str, Any]) -> str:
    rows: list[str] = []
    for key in evidence:
        if key in _SKIP_EVIDENCE_KEYS:
            continue
        rows.append(f"<div><dt>{_e(key)}</dt><dd>{_render_value(evidence[key])}</dd></div>")
    if not rows:
        return ""
    return f'<dl class="evidence">{"".join(rows)}</dl>'


def _render_value(value: Any) -> str:
    if value is None:
        return '<span class="muted">n/a</span>'
    if isinstance(value, bool):
        return _e("true" if value else "false")
    if isinstance(value, int | float):
        return _e(value)
    if isinstance(value, str):
        return f"<code>{_e(value)}</code>" if _looks_like_path(value) else _e(value)
    if isinstance(value, list | tuple):
        if not value:
            return '<span class="muted">none</span>'
        if all(isinstance(item, str) for item in value):
            items = "".join(f"<li><code>{_e(item)}</code></li>" for item in value)
            return f'<ul class="paths">{items}</ul>'
        items = "".join(f"<li>{_render_value(item)}</li>" for item in value)
        return f"<ul>{items}</ul>"
    if isinstance(value, dict):
        inner = "".join(
            f"<div><dt>{_e(k)}</dt><dd>{_render_value(v)}</dd></div>" for k, v in value.items()
        )
        return f'<dl class="nested">{inner}</dl>'
    return _e(value)


def _looks_like_path(value: str) -> bool:
    return "/" in value or value.endswith((".txt", ".md", ".pdf", ".html", ".htm", ".docx"))


def _config_table(config: dict[str, Any]) -> str:
    rows = "".join(f"<tr><th>{_e(key)}</th><td>{_e(config[key])}</td></tr>" for key in config)
    return f'<table class="stats"><tbody>{rows}</tbody></table>'


def _fmt_float(value: float) -> str:
    if value == 0:
        return "0"
    return f"{value:.1f}"


def _fmt_optional_int(value: int | None) -> str:
    return "n/a" if value is None else str(value)


_CSS = (
    ":root{color-scheme:light}"
    "*{box-sizing:border-box}"
    "body{margin:0 auto;max-width:52rem;padding:2rem 1.25rem 3rem;"
    "font:16px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif;"
    "color:#1a1a1a;background:#f6f4f0}"
    "header,section,footer{margin-bottom:2rem}"
    ".eyebrow{margin:0;letter-spacing:.08em;text-transform:uppercase;"
    "font-size:.75rem;color:#5c574f}"
    "h1{margin:.35rem 0 .75rem;font-size:1.85rem}"
    "h2{margin:0 0 .75rem;font-size:1.2rem;border-bottom:1px solid #d9d3c8;"
    "padding-bottom:.35rem}"
    "h3{margin:1.25rem 0 .5rem;font-size:1.05rem}"
    "h4{margin:.35rem 0 .5rem;font-size:1.05rem}"
    "h5{margin:.85rem 0 .35rem;font-size:.85rem;text-transform:uppercase;"
    "letter-spacing:.04em;color:#5c574f}"
    ".lede,footer p,.muted{color:#5c574f}"
    ".muted{font-size:.92rem}"
    ".mono,code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}"
    "code{font-size:.9em;word-break:break-word}"
    "table.stats{width:100%;border-collapse:collapse;background:#fff}"
    "table.stats th,table.stats td{text-align:left;padding:.45rem .7rem;"
    "border-bottom:1px solid #ece7de}"
    "table.stats th{width:60%;font-weight:600}"
    "dl.meta,dl.evidence,dl.nested{display:grid;gap:.35rem 1rem}"
    "dl.meta>div,dl.evidence>div,dl.nested>div{display:grid;"
    "grid-template-columns:minmax(8rem,32%) 1fr;gap:.35rem 1rem}"
    "dt{font-weight:600}"
    "dd{margin:0}"
    "ul.paths,ul{margin:.25rem 0 0;padding-left:1.2rem}"
    ".finding{background:#fff;border:1px solid #e4ddd2;padding:1rem 1.1rem;margin:.75rem 0}"
    ".sev{display:inline-block;padding:.1rem .45rem;font-size:.75rem;"
    "font-weight:700;letter-spacing:.04em}"
    ".sev-high{background:#f8d0c8;color:#7a1f12}"
    ".sev-medium{background:#f7e1b5;color:#6d4a00}"
    ".sev-low{background:#d5e4f5;color:#1d3f6e}"
    ".sev-info{background:#e3e3e3;color:#333}"
    "footer{font-size:.9rem}"
)
